name: Android Build
on: [push]
defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest
    name: build debug
    if: "!contains(toJSON(github.event.commits.*.message), '[skip action]') && !startsWith(github.ref, 'refs/tags/')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
#      - name: Gradle cache
#        uses: actions/cache@v2
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#      - name: Build debug
#        run: ./gradlew assembleDebug
#      - name: Archive artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          path: app/build/outputs
      - name: Notify KakaoWork channel
        run: |
          curl -X POST https://api.kakaowork.com/v1/messages.send \
          -H "Authorization: Bearer 6416d234.9f1917530fd34a659315d64e3264b77c" \
          -H "Content-Type: application/json" \
          -d "{ \"conversation_id\": \"695731\", \"text\": \"안드로이드 디버그 빌드 성공 깃허브에서 apk를 다운로드 받으세요\" }"
